/**
 * Sayanox Edge — cache header generation
 * Produces a `_headers` file understood by Cloudflare Pages / Netlify.
 */

/**
 * Strong, deploy-ready cache rules for static sites.
 * Hashed assets get immutable 1-year caching; HTML stays fresh.
 */
export function buildHeadersFile() {
  return `# Generated by Sayanox Edge ⚡ (sayanox-edge)
# Works with Cloudflare Pages & Netlify. For Vercel use vercel.json headers.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=()
  X-Frame-Options: SAMEORIGIN

# HTML — always revalidate so visitors get updates instantly
/*.html
  Cache-Control: public, max-age=0, must-revalidate

/index.html
  Cache-Control: public, max-age=0, must-revalidate

/css/
  Cache-Control: public, max-age=31536000, immutable

/js/
  Cache-Control: public, max-age=31536000, immutable

/images/
  Cache-Control: public, max-age=31536000, immutable

/img/
  Cache-Control: public, max-age=31536000, immutable

/fonts/
  Cache-Control: public, max-age=31536000, immutable

*.woff2
  Cache-Control: public, max-age=31536000, immutable

*.jpg
  Cache-Control: public, max-age=31536000, immutable

*.jpeg
  Cache-Control: public, max-age=31536000, immutable

*.png
  Cache-Control: public, max-age=31536000, immutable

*.webp
  Cache-Control: public, max-age=31536000, immutable

*.svg
  Cache-Control: public, max-age=604800, stale-while-revalidate=86400

*.css
  Cache-Control: public, max-age=31536000, immutable

*.js
  Cache-Control: public, max-age=31536000, immutable
`;
}

/**
 * A vercel.json snippet for users deploying to Vercel (informational).
 */
export function buildVercelHeadersConfig() {
  return JSON.stringify(
    {
      headers: [
        {
          source: '/(.*)',
          headers: [
            { key: 'X-Content-Type-Options', value: 'nosniff' },
            { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          ],
        },
        {
          source: '/(css|js|images|img|fonts)/(.*)',
          headers: [
            { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
          ],
        },
        {
          source: '/((?!.*\\.).*)',
          headers: [{ key: 'Cache-Control', value: 'public, max-age=0, must-revalidate' }],
        },
      ],
    },
    null,
    2
  );
}
